# Generated by Django 5.1.2 on 2025-01-07 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
